"""add meal_time

Revision ID: 1180eeb792c7
Revises: be67c74b7fb2
Create Date: 2025-03-09 16:25:35.567363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1180eeb792c7'
down_revision: Union[str, None] = 'be67c74b7fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
meal_time_enum = postgresql.ENUM('BREAKFAST', 'BRUNCH', 'LUNCH', 'LINNER', 'DINNER', 'SNACK', name='mealtime', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Food',
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=26), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('calorie', sa.Float(), nullable=True),
    sa.Column('carb', sa.Float(), nullable=True),
    sa.Column('sugar', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('calcium', sa.Float(), nullable=True),
    sa.Column('phosphorus', sa.Float(), nullable=True),
    sa.Column('sodium', sa.Float(), nullable=True),
    sa.Column('potassium', sa.Float(), nullable=True),
    sa.Column('magnesium', sa.Float(), nullable=True),
    sa.Column('iron', sa.Float(), nullable=True),
    sa.Column('zinc', sa.Float(), nullable=True),
    sa.Column('cholesterol', sa.Float(), nullable=True),
    sa.Column('trans_fat', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('label', name=op.f('pk_Food'))
    )
    op.create_table('MealHour',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('daymeal_id', sa.String(length=26), nullable=False),
    sa.Column('meal_time', meal_time_enum, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('picture', sa.String(length=255), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('record_datetime', sa.DateTime(), nullable=False),
    sa.Column('heart', sa.Boolean(), nullable=True),
    sa.Column('carb', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('calorie', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('track_goal', sa.Boolean(), nullable=True),
    sa.Column('label', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['daymeal_id'], ['MealDay.id'], name=op.f('fk_MealHour_daymeal_id_MealDay')),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_MealHour_user_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_MealHour')),
    sa.UniqueConstraint('daymeal_id', 'meal_time', name='_mealday_time_uc')
    )
    op.create_index(op.f('ix_MealHour_picture'), 'MealHour', ['picture'], unique=False)
    op.create_index('_user_date_index', 'MealDay', ['user_id', 'record_date'], unique=False)
    op.alter_column('User', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', name='gender'),
               nullable=True)
    op.alter_column('User', 'birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('User', 'profile_picture',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('User', 'fcm_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'fcm_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('User', 'profile_picture',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('User', 'birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('User', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', name='gender'),
               nullable=False)
    op.drop_index('_user_date_index', table_name='MealDay')
    op.drop_index(op.f('ix_MealHour_picture'), table_name='MealHour')
    op.drop_table('MealHour')
    op.drop_table('Food')
    # ### end Alembic commands ###
