"""add routinefood id

Revision ID: dbc17e082d04
Revises: e087e7e59628
Create Date: 2025-04-13 17:20:50.295370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc17e082d04'
down_revision: Union[str, None] = 'e087e7e59628'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RoutineFood', sa.Column('id', sa.String(length=26), nullable=False))
    op.add_column('RoutineFood', sa.Column('food_label', sa.Integer(), nullable=False))
    op.drop_constraint('fk_RoutineFood_food_id_Food', 'RoutineFood', type_='foreignkey')
    op.create_foreign_key(op.f('fk_RoutineFood_food_label_Food'), 'RoutineFood', 'Food', ['food_label'], ['label'], ondelete='CASCADE')
    op.drop_column('RoutineFood', 'food_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RoutineFood', sa.Column('food_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_RoutineFood_food_label_Food'), 'RoutineFood', type_='foreignkey')
    op.create_foreign_key('fk_RoutineFood_food_id_Food', 'RoutineFood', 'Food', ['food_id'], ['label'], ondelete='CASCADE')
    op.drop_column('RoutineFood', 'food_label')
    op.drop_column('RoutineFood', 'id')
    # ### end Alembic commands ###
