"""add routinefood unique

Revision ID: 834dc86c4ece
Revises: dbc17e082d04
Create Date: 2025-04-13 18:47:17.801386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '834dc86c4ece'
down_revision: Union[str, None] = 'dbc17e082d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_routine_food_pair', 'RoutineFood', ['track_routine_id', 'food_label'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_routine_food_pair', 'RoutineFood', type_='unique')
    # ### end Alembic commands ###
