"""add routine&food check

Revision ID: 137d9bbf938d
Revises: e56a098514b1
Create Date: 2025-04-15 00:53:38.112145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '137d9bbf938d'
down_revision: Union[str, None] = 'e56a098514b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dish',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('mealday_id', sa.String(length=26), nullable=False),
    sa.Column('mealtime', sa.Enum('BREAKFAST', 'BRUNCH', 'LUNCH', 'LINNER', 'DINNER', 'SNACK', name='mealtime'), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('picture', sa.String(length=255), nullable=True),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('record_datetime', sa.DateTime(), nullable=False),
    sa.Column('update_datetime', sa.DateTime(), nullable=False),
    sa.Column('heart', sa.Boolean(), nullable=True),
    sa.Column('carb', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('calorie', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('track_goal', sa.Boolean(), nullable=True),
    sa.Column('label', sa.Integer(), nullable=True),
    sa.Column('trackpart_id', sa.String(length=26), nullable=True),
    sa.ForeignKeyConstraint(['mealday_id'], ['MealDay.id'], name=op.f('fk_Dish_mealday_id_MealDay')),
    sa.ForeignKeyConstraint(['trackpart_id'], ['TrackParticipant.id'], name=op.f('fk_Dish_trackpart_id_TrackParticipant')),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Dish_user_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Dish'))
    )
    op.create_index(op.f('ix_Dish_picture'), 'Dish', ['picture'], unique=False)
    op.create_table('RoutineFood',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('routine_id', sa.String(), nullable=False),
    sa.Column('food_label', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['food_label'], ['Food.label'], name=op.f('fk_RoutineFood_food_label_Food'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['routine_id'], ['TrackRoutine.id'], name=op.f('fk_RoutineFood_routine_id_TrackRoutine'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_RoutineFood')),
    sa.UniqueConstraint('routine_id', 'food_label', name='uq_routine_food_pair')
    )
    op.create_table('RoutineFoodCheck',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('routine_food_id', sa.String(length=26), nullable=False),
    sa.Column('dish_id', sa.String(length=26), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('check_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['Dish.id'], name=op.f('fk_RoutineFoodCheck_dish_id_Dish'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['routine_food_id'], ['RoutineFood.id'], name=op.f('fk_RoutineFoodCheck_routine_food_id_RoutineFood'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_RoutineFoodCheck')),
    sa.UniqueConstraint('routine_food_id', 'dish_id', name='uq_routine_dish_pair')
    )
    op.add_column('TrackRoutine', sa.Column('mealtime', sa.Enum('BREAKFAST', 'BRUNCH', 'LUNCH', 'LINNER', 'DINNER', 'SNACK', name='mealtime'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TrackRoutine', 'mealtime')
    op.drop_table('RoutineFoodCheck')
    op.drop_table('RoutineFood')
    op.drop_index(op.f('ix_Dish_picture'), table_name='Dish')
    op.drop_table('Dish')
    # ### end Alembic commands ###
