"""revision mealday

Revision ID: cdf83c5514e3
Revises: eb80287ee85d
Create Date: 2025-04-02 11:57:36.911579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdf83c5514e3'
down_revision: Union[str, None] = 'eb80287ee85d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
meal_time_enum = postgresql.ENUM('BREAKFAST', 'BRUNCH', 'LUNCH', 'LINNER', 'DINNER', 'SNACK', name='mealtime', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Food',
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=26), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('calorie', sa.Float(), nullable=True),
    sa.Column('carb', sa.Float(), nullable=True),
    sa.Column('sugar', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('calcium', sa.Float(), nullable=True),
    sa.Column('phosphorus', sa.Float(), nullable=True),
    sa.Column('sodium', sa.Float(), nullable=True),
    sa.Column('potassium', sa.Float(), nullable=True),
    sa.Column('magnesium', sa.Float(), nullable=True),
    sa.Column('iron', sa.Float(), nullable=True),
    sa.Column('zinc', sa.Float(), nullable=True),
    sa.Column('cholesterol', sa.Float(), nullable=True),
    sa.Column('trans_fat', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('label', name=op.f('pk_Food'))
    )
    op.create_table('Meal',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('mealday_id', sa.String(length=26), nullable=False),
    sa.Column('mealtime', meal_time_enum, nullable=False),
    sa.Column('check', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mealday_id'], ['MealDay.id'], name=op.f('fk_Meal_mealday_id_MealDay')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Meal')),
    sa.UniqueConstraint('mealday_id', 'mealtime', name='_mealday_id_mealtime_uc')
    )
    op.create_table('Dish',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('meal_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('picture', sa.String(length=255), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.Column('record_datetime', sa.DateTime(), nullable=False),
    sa.Column('update_datetime', sa.DateTime(), nullable=False),
    sa.Column('heart', sa.Boolean(), nullable=True),
    sa.Column('carb', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('calorie', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('track_goal', sa.Boolean(), nullable=True),
    sa.Column('label', sa.Integer(), nullable=True),
    sa.Column('trackpart_id', sa.String(length=26), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['Meal.id'], name=op.f('fk_Dish_meal_id_Meal')),
    sa.ForeignKeyConstraint(['trackpart_id'], ['TrackParticipant.id'], name=op.f('fk_Dish_trackpart_id_TrackParticipant')),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Dish_user_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Dish'))
    )
    op.create_index(op.f('ix_Dish_picture'), 'Dish', ['picture'], unique=False)
    op.add_column('MealDay', sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_index('_user_date_index', 'MealDay', ['user_id', 'record_date'], unique=False)
    op.drop_column('TrackRoutine', 'meal_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TrackRoutine', sa.Column('meal_time', postgresql.ENUM('BREAKFAST', 'BRUNCH', 'LUNCH', 'LINNER', 'DINNER', 'SNACK', name='mealtime'), autoincrement=False, nullable=False))
    op.drop_index('_user_date_index', table_name='MealDay')
    op.drop_column('MealDay', 'update_datetime')
    op.drop_index(op.f('ix_Dish_picture'), table_name='Dish')
    op.drop_table('Dish')
    op.drop_table('Meal')
    op.drop_table('Food')
    # ### end Alembic commands ###
