"""add routine food

Revision ID: 74c90b953283
Revises: 25a44c24c652
Create Date: 2025-04-13 15:37:59.563587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c90b953283'
down_revision: Union[str, None] = '25a44c24c652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RoutineFood',
    sa.Column('track_routine_id', sa.String(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['Food.label'], name=op.f('fk_RoutineFood_food_id_Food'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_routine_id'], ['TrackRoutine.id'], name=op.f('fk_RoutineFood_track_routine_id_TrackRoutine'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_routine_id', 'food_id', name=op.f('pk_RoutineFood'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RoutineFood')
    # ### end Alembic commands ###
