"""add quantity and casecade

Revision ID: 25a44c24c652
Revises: 5398f4c41d48
Create Date: 2025-04-13 15:21:54.776583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25a44c24c652'
down_revision: Union[str, None] = '5398f4c41d48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TrackRoutine_Food')
    op.drop_constraint('fk_Track_origin_track_id_Track', 'Track', type_='foreignkey')
    op.create_foreign_key(op.f('fk_Track_origin_track_id_Track'), 'Track', 'Track', ['origin_track_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_Track_origin_track_id_Track'), 'Track', type_='foreignkey')
    op.create_foreign_key('fk_Track_origin_track_id_Track', 'Track', 'Track', ['origin_track_id'], ['id'])
    op.create_table('TrackRoutine_Food',
    sa.Column('track_routine_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('food_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['Food.label'], name='fk_TrackRoutine_Food_food_id_Food'),
    sa.ForeignKeyConstraint(['track_routine_id'], ['TrackRoutine.id'], name='fk_TrackRoutine_Food_track_routine_id_TrackRoutine'),
    sa.PrimaryKeyConstraint('track_routine_id', 'food_id', name='pk_TrackRoutine_Food')
    )
    # ### end Alembic commands ###
