"""add track participant

Revision ID: 896e78a71cda
Revises: f3684bfdee51
Create Date: 2025-03-25 14:01:49.974058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896e78a71cda'
down_revision: Union[str, None] = 'f3684bfdee51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TrackParticipant',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['Track.id'], name=op.f('fk_TrackParticipant_track_id_Track'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_TrackParticipant_user_id_User'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_TrackParticipant'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TrackParticipant')
    # ### end Alembic commands ###
