"""change mealtime type

Revision ID: b6139af16920
Revises: 18d5068076dd
Create Date: 2025-03-31 22:13:29.379572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6139af16920'
down_revision: Union[str, None] = '18d5068076dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TrackRoutine', sa.Column('mealtime', sa.Enum('BREAKFAST', 'BRUNCH', 'LUNCH', 'LINNER', 'DINNER', 'SNACK', name='mealtime'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TrackRoutine', 'mealtime')
    # ### end Alembic commands ###
