"""add track

Revision ID: af221a33be71
Revises: 638489b9293c
Create Date: 2025-02-02 00:38:02.529879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af221a33be71'
down_revision: Union[str, None] = '638489b9293c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Track',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('origin_track_id', sa.String(length=26), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('water', sa.Float(), nullable=False),
    sa.Column('coffee', sa.Float(), nullable=False),
    sa.Column('alcohol', sa.Float(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.Column('cheating_count', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('finish_date', sa.Date(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=False),
    sa.Column('alone', sa.Boolean(), nullable=False),
    sa.Column('daily_calorie', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['origin_track_id'], ['Track.id'], name=op.f('fk_Track_origin_track_id_Track')),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Track_user_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Track'))
    )
    op.create_table('TrackRoutine',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('track_id', sa.String(length=26), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('calorie', sa.Float(), nullable=False),
    sa.Column('delete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['Track.id'], name=op.f('fk_TrackRoutine_track_id_Track')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_TrackRoutine'))
    )
    op.create_table('TrackRoutineDate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('routine_id', sa.String(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('meal_time', sa.Enum('BREAKFAST', 'BRUNCH', 'LUNCH', 'LINNER', 'DINNER', 'SNACK', name='mealtime'), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.Column('clock', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['TrackRoutine.id'], name=op.f('fk_TrackRoutineDate_routine_id_TrackRoutine')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_TrackRoutineDate'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TrackRoutineDate')
    op.drop_table('TrackRoutine')
    op.drop_table('Track')
    # ### end Alembic commands ###
