"""add mealday

Revision ID: be67c74b7fb2
Revises: 2c56ec5a6899
Create Date: 2025-02-27 20:37:47.637104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be67c74b7fb2'
down_revision: Union[str, None] = '2c56ec5a6899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MealDay',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('water', sa.Float(), nullable=True),
    sa.Column('coffee', sa.Float(), nullable=True),
    sa.Column('alcohol', sa.Float(), nullable=True),
    sa.Column('carb', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('cheating', sa.Integer(), nullable=True),
    sa.Column('goalcalorie', sa.Float(), nullable=True),
    sa.Column('nowcalorie', sa.Float(), nullable=True),
    sa.Column('burncalorie', sa.Float(), nullable=True),
    sa.Column('gb_carb', sa.String(length=10), nullable=True),
    sa.Column('gb_protein', sa.String(length=10), nullable=True),
    sa.Column('gb_fat', sa.String(length=10), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('routine_success_rate', sa.Float(), nullable=True),
    sa.Column('track_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['Track.id'], name=op.f('fk_MealDay_track_id_Track')),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_MealDay_user_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_MealDay')),
    sa.UniqueConstraint('user_id', 'record_date', name='_user_date_daily_uc')
    )
    op.alter_column('User', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', name='gender'),
               nullable=False)
    op.alter_column('User', 'birth',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('User', 'profile_picture',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('User', 'fcm_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'fcm_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('User', 'profile_picture',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('User', 'birth',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('User', 'gender',
               existing_type=postgresql.ENUM('MALE', 'FEMALE', name='gender'),
               nullable=True)
    op.drop_table('MealDay')
    # ### end Alembic commands ###
