"""add username unique

Revision ID: 48cd5c5c4056
Revises: 610d5b57aa9d
Create Date: 2025-01-17 03:27:46.942048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48cd5c5c4056'
down_revision: Union[str, None] = '610d5b57aa9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_User_username'), 'User', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_User_username'), 'User', type_='unique')
    # ### end Alembic commands ###
