"""add user

Revision ID: 34c36e203dc9
Revises: eb712c3b6bc3
Create Date: 2025-01-13 17:44:07.087424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c36e203dc9'
down_revision: Union[str, None] = 'eb712c3b6bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cellphone', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=False),
    sa.Column('birth', sa.DateTime(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('rank', sa.String(length=255), nullable=False),
    sa.Column('profile_picture', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('auth_type', sa.String(length=255), nullable=False),
    sa.Column('fcm_token', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'TRAINER', 'ADMIN', name='role'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_User')),
    sa.UniqueConstraint('cellphone', name=op.f('uq_User_cellphone')),
    sa.UniqueConstraint('email', name=op.f('uq_User_email')),
    sa.UniqueConstraint('nickname', name=op.f('uq_User_nickname'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
