"""change user

Revision ID: c6d410aaf79a
Revises: 34c36e203dc9
Create Date: 2025-01-15 04:55:21.387143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6d410aaf79a'
down_revision: Union[str, None] = '34c36e203dc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('update_date', sa.DateTime(), nullable=False))
    op.alter_column('User', 'gender',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('User', 'birth',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.drop_column('User', 'external_id')
    op.drop_column('User', 'auth_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('auth_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('external_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('User', 'birth',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('User', 'gender',
               existing_type=sa.String(length=255),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    op.drop_column('User', 'update_date')
    # ### end Alembic commands ###
