"""merge routine routinedate

Revision ID: 0245c8f35e82
Revises: 21fbe4440b7d
Create Date: 2025-03-31 20:49:08.631602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0245c8f35e82'
down_revision: Union[str, None] = '21fbe4440b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TrackRoutineDate')
    op.add_column('TrackParticipant', sa.Column('finished', sa.Boolean(), nullable=False))
    op.add_column('TrackRoutine', sa.Column('weekday', sa.Integer(), nullable=False))
    op.add_column('TrackRoutine', sa.Column('meal_time', sa.Enum('BREAKFAST', 'BRUNCH', 'LUNCH', 'LINNER', 'DINNER', 'SNACK', name='mealtime'), nullable=False))
    op.add_column('TrackRoutine', sa.Column('days', sa.Integer(), nullable=False))
    op.add_column('TrackRoutine', sa.Column('clock', sa.Time(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TrackRoutine', 'clock')
    op.drop_column('TrackRoutine', 'days')
    op.drop_column('TrackRoutine', 'meal_time')
    op.drop_column('TrackRoutine', 'weekday')
    op.drop_column('TrackParticipant', 'finished')
    op.create_table('TrackRoutineDate',
    sa.Column('id', sa.VARCHAR(), server_default=sa.text('nextval(\'"TrackRoutineDate_id_seq"\'::regclass)'), autoincrement=False, nullable=False),
    sa.Column('routine_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('weekday', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('meal_time', postgresql.ENUM('BREAKFAST', 'BRUNCH', 'LUNCH', 'LINNER', 'DINNER', 'SNACK', name='mealtime'), autoincrement=False, nullable=False),
    sa.Column('date', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('clock', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['TrackRoutine.id'], name='fk_TrackRoutineDate_routine_id_TrackRoutine'),
    sa.PrimaryKeyConstraint('id', name='pk_TrackRoutineDate')
    )
    # ### end Alembic commands ###
