"""add routine check food user_id

Revision ID: 5bdd883ba802
Revises: 293eedf9bec7
Create Date: 2025-04-16 02:11:32.206319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bdd883ba802'
down_revision: Union[str, None] = '293eedf9bec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('RoutineFoodCheck', sa.Column('user_id', sa.String(length=26), nullable=False))
    op.create_foreign_key(op.f('fk_RoutineFoodCheck_user_id_User'), 'RoutineFoodCheck', 'User', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_RoutineFoodCheck_user_id_User'), 'RoutineFoodCheck', type_='foreignkey')
    op.drop_column('RoutineFoodCheck', 'user_id')
    # ### end Alembic commands ###
