"""mealtime

Revision ID: 6b9cc2f3ce8d
Revises: 731484971472
Create Date: 2025-05-29 02:46:13.258271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b9cc2f3ce8d'
down_revision: Union[str, None] = '731484971472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Dish', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('Dish', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.drop_index('ix_Dish_picture', table_name='Dish')
    op.create_index(op.f('ix_Dish_image_url'), 'Dish', ['image_url'], unique=False)
    op.create_foreign_key(op.f('fk_Dish_label_Food'), 'Dish', 'Food', ['label'], ['label'])
    op.drop_column('Dish', 'picture')
    op.drop_column('TrackRoutine', 'meal_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TrackRoutine', sa.Column('meal_time', postgresql.ENUM('BREAKFAST', 'BRUNCH', 'LUNCH', 'LINNER', 'DINNER', 'SNACK', name='mealtime'), autoincrement=False, nullable=False))
    op.add_column('Dish', sa.Column('picture', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_Dish_label_Food'), 'Dish', type_='foreignkey')
    op.drop_index(op.f('ix_Dish_image_url'), table_name='Dish')
    op.create_index('ix_Dish_picture', 'Dish', ['picture'], unique=False)
    op.drop_column('Dish', 'image_url')
    op.drop_column('Dish', 'quantity')
    # ### end Alembic commands ###
