"""add track participant unique

Revision ID: 21fbe4440b7d
Revises: 896e78a71cda
Create Date: 2025-03-25 15:14:02.659550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21fbe4440b7d'
down_revision: Union[str, None] = '896e78a71cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_TrackParticipant_track_id'), 'TrackParticipant', ['track_id'])
    op.create_unique_constraint(op.f('uq_TrackParticipant_user_id'), 'TrackParticipant', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_TrackParticipant_user_id'), 'TrackParticipant', type_='unique')
    op.drop_constraint(op.f('uq_TrackParticipant_track_id'), 'TrackParticipant', type_='unique')
    # ### end Alembic commands ###
