"""add routine check

Revision ID: 293eedf9bec7
Revises: 137d9bbf938d
Create Date: 2025-04-15 23:54:22.564356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '293eedf9bec7'
down_revision: Union[str, None] = '137d9bbf938d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RoutineCheck',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('routine_id', sa.String(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('check_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['TrackRoutine.id'], name=op.f('fk_RoutineCheck_routine_id_TrackRoutine'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_RoutineCheck_user_id_User'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_RoutineCheck')),
    sa.UniqueConstraint('routine_id', 'user_id', name='uq_routine_user_pair')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('RoutineCheck')
    # ### end Alembic commands ###
