"""del column routine weekday

Revision ID: 18d5068076dd
Revises: 0245c8f35e82
Create Date: 2025-03-31 21:40:01.501322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d5068076dd'
down_revision: Union[str, None] = '0245c8f35e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TrackRoutine', 'weekday')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TrackRoutine', sa.Column('weekday', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
