"""add col image url

Revision ID: eb80287ee85d
Revises: b6139af16920
Create Date: 2025-04-01 00:19:38.097326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb80287ee85d'
down_revision: Union[str, None] = 'b6139af16920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Track', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('TrackRoutine', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TrackRoutine', 'image_url')
    op.drop_column('Track', 'image_url')
    # ### end Alembic commands ###
