"""fix rout_date_id

Revision ID: 2c56ec5a6899
Revises: af221a33be71
Create Date: 2025-02-02 05:10:35.723314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c56ec5a6899'
down_revision: Union[str, None] = 'af221a33be71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TrackRoutineDate', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"TrackRoutineDate_id_seq"\'::regclass)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TrackRoutineDate', 'id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('nextval(\'"TrackRoutineDate_id_seq"\'::regclass)'))
    # ### end Alembic commands ###
