"""add food col image_url

Revision ID: 731484971472
Revises: 5bdd883ba802
Create Date: 2025-04-16 17:14:39.996739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '731484971472'
down_revision: Union[str, None] = '5bdd883ba802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Food', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_Food_image_url'), 'Food', ['image_url'], unique=False)
    op.alter_column('RoutineFood', 'food_label',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('RoutineFood', 'food_label',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_Food_image_url'), table_name='Food')
    op.drop_column('Food', 'image_url')
    # ### end Alembic commands ###
