"""connect routine food

Revision ID: 5398f4c41d48
Revises: cdf83c5514e3
Create Date: 2025-04-13 14:56:49.218096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5398f4c41d48'
down_revision: Union[str, None] = 'cdf83c5514e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TrackRoutine_Food',
    sa.Column('track_routine_id', sa.String(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['Food.label'], name=op.f('fk_TrackRoutine_Food_food_id_Food')),
    sa.ForeignKeyConstraint(['track_routine_id'], ['TrackRoutine.id'], name=op.f('fk_TrackRoutine_Food_track_routine_id_TrackRoutine')),
    sa.PrimaryKeyConstraint('track_routine_id', 'food_id', name=op.f('pk_TrackRoutine_Food'))
    )
    op.drop_column('Track', 'water')
    op.drop_column('Track', 'alcohol')
    op.drop_column('Track', 'coffee')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Track', sa.Column('coffee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('Track', sa.Column('alcohol', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('Track', sa.Column('water', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_table('TrackRoutine_Food')
    # ### end Alembic commands ###
